---
#  - name: 'test_vars priortiy'
#    hosts: testvars
#    vars:
#      #test_vars: "getvar.yml"
#
#    roles:
#      - vartest

#  - name: "grammar learning"
#    hosts: test
#
#    roles:
#      - grammar

#  - name: "var read"
#    hosts: "{{ thisServer }}"
#    roles:
#      - varread
#
#  - name: test module
#    hosts: testvars
#    roles:
#      - moduleTest

  - name: templateTest
    hosts: testvars
    roles:
      - templateTest
