---
  # touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  - file: path="{{ filepath }}/file1.conf" state=touch mode="u=rw,g=r,o=r"

  # touch the same file, but add/remove some permissions
  - file: path="{{ filepath }}/file2.conf" state=touch mode="u+rw,g-wx,o-rwx"

  # create a directory if it doesn't exist
  - file: path="{{ filepath }}/file_directory" state=directory mode=0755
