---
  - name: "download site.tar.gz from github.com"
    get_url:
      url: "https://github.com/weston100721/maven-plugin-example/releases/download/1.0-SNAPSHOT/site.tar.gz"
      dest: "{{ filepath }}"
