---
  - name: "创建目录"
    file: path="{{ tempfile }}" state=directory mode=0755
# tasks file for roles/templateTest

  - name: Copy nginx configuration in place.
    template:
      src: nginx.conf.j2
      dest: "{{ tempfile }}/nginx.conf"
      owner: zhaoliang
      group: zhaoliang
      mode: 0644
